<?php
  $girls = [
    [ 'id' => '1',
      'premium' => true, 
      'premium-type'=>'premium-s',
      'store'=>'梅田',
      'name'=>'かりん',
      'age'=>'28',
      'img' => '1',
      'time' => '10:00-14:00',
      'tall' => '162',
      'bust' => '90-H',
      'waist' => '60',
      'height' => '81',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => true, 
      'kuchikomi-name' => 'ピーヤ007', 
      'kuchikomi-star' => '★★★★★', 
      'kuchikomi-title' => 'まさに理想のおっぱいと愛想の良さ', 
      'kuchikomi-comment' => '若くて巨乳の女の子を探していたところ、偶然この子を発見。<br>
      自分のタイプとドンピシャな見た目だったのでスグに予約状況を確認して当日予約に成功。
        <br><br>
        いざご対面。。<br>
        なんだ!!この可愛さは!!そして何より誰が見てもわかる服の上からロケットボイン。<br>
        スグに予約をして良かった！と、胸が踊りながら大きなGカップを腕にグッと寄せて恋人気分の様にテクテクとホテルへ...',
      'sun' => false,
      'mon' => true,
      'tue' => false,
      'wed' => false,
      'thu' => true,
      'fri' => true,
      'sat' => false,
      'date' => '',
      'comment' => 'お勧め超美人セラピスト<br>
      センス抜群妖艶さ満天！<br>言葉責めが得意で密着に自信あり！',
            'food' => '中華',
      'character' => '元気',
      'type' => '優しい人',
      'cast-name' => 'もえ',
      'tag1' => 'ミニマム',
      'tag2' => '業界未経験',
      'tag3' => '清楚系',
      'cast-comment' => '楽しい時間を過ごしましょー!!いっぱい仲良くなろうねっ',
      'store-comment' => '業界未経験、本当にウブという言葉がぴったりの元気っ子。<br>
      紳士的な方に指導願います！' ,
      'cast-comment-tab' => '楽しい時間を過ごしましょー!!<br>
      いっぱい仲良くなろうねっ',
      'store-comment-tab' => '業界未経験、本当にウブという言葉が<br>
      ぴったりの元気っ子。<br>
      紳士的な方に指導願います！' 

    ],[
      'id' => '2',
      'premium' =>  true, 
      'premium-type'=>'premium-g',
      'store'=>'京橋',
      'name'=>'えりか',
      'age'=>'25',
      'img' => '2',
      'time' => '10:00-15:00',
      'tall' => '156',
      'bust' => '86-C',
      'waist' => '59',
      'height' => '85',
      'newface' => true  , 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => false,
      'tue' => false,
      'wed' => true,
      'thu' => false,
      'fri' => true,
      'sat' => false,
      'date' => '05/04',
      'comment' => '全身を使ったオイルマッサージは<br>トロトロオイルと相性抜群！極みの<br>マッサージをご体感ください。',
            'food' => '和菓子',
      'character' => '不思議ちゃん',
      'type' => '素直な人',
      'cast-name' => 'えみ',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => '清楚系',
      'cast-comment' => '優しくご指導してくれる先生お待ちしてますっ♪',
      'store-comment' => '不思議系美少女！<br>
      その少し含みのある天使の微笑みに身を任せてみませんか？',
      'cast-comment-tab' => '優しくご指導してくれる先生<br>
      お待ちしてますっ♪',
      'store-comment-tab' => '不思議系美少女！<br>
      その少し含みのある天使の微笑みに<br>
      身を任せてみませんか？'
      
    ],[
      'id' => '3',
      'premium' => true, 
      'premium-type'=>'premium-r',
      'store'=>'日本橋',
      'name'=>'もも',
      'age'=>'21',
      'img' => '3',
      'time' => '10:00-15:00',
      'tall' => '160',
      'bust' => '90-F',
      'waist' => '62',
      'height' => '85',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => true, 
      'kuchikomi-name' => '92魔王', 
      'kuchikomi-star' => '★★★★', 
      'kuchikomi-title' => '綺麗＆可愛いが揃ったメチャかわ女子', 
      'kuchikomi-comment' => '口コミは初投稿になります。<br>
      ずっと気になっていた女の子だったので、電話予約をして店舗の方へ。<br><br>
      対面の際はマスク越しですが笑顔がとても可愛く、ご丁寧に接してくれて良かったです。
      そして良い匂い…。<br>
      ホテルまで向かう最中も、こちらの腕をギュっと組んで軽くムクっと反応しながら雑談をしてお部屋に到着。
      室内で二人きりになった途端に…。',
      'sun' => false,
      'mon' => true,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => true,
      'sat' => false,
      'date' => '',
      'comment' => 'とにかく可愛い！！素人未経験とは<br>思えない技術レベルで実技講習も<br>
      さらっとこなす！期待大の超新星！',
            'food' => 'スイーツ',
      'character' => '真面目',
      'type' => '優しい人',
      'cast-name' => 'ひとみ',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => '癒し系',
      'cast-comment' => 'メッチャ緊張してますがよろしくお願いします！',
      'store-comment' => '毛先までサラサラのロングヘアー、整った顔立ち、いつまでも<br>
      消えない初々しさ、生まれ持っての引力の強さが半端ない!!',
      'cast-comment-tab' => 'メッチャ緊張してますが<br>
      よろしくお願いします！',
      'store-comment-tab' => '毛先までサラサラのロングヘアー<br>
      整った顔立ち、いつまでも<br>
      消えない初々しさ、生まれ持っての<br>
      引力の強さが半端ない!!'
    ],[   
      'id' => '4',  
      'premium' => true, 
      'premium-type'=>'premium-b',
      'store'=>'京橋',
      'name'=>'れいか',
      'age'=>'25',
      'img' => '4',
      'time' => '10:00-15:00',
      'tall' => '158',
      'bust' => '84-C',
      'waist' => '60',
      'height' => '85',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => true, 
      'sun' => false,
      'sun' => true,
      'mon' => false,
      'tue' => false,
      'wed' => true,
      'thu' => false,
      'fri' => true,
      'sat' => false ,
      'date' => '',
      'comment' => '最高に可愛く！最高の気配り！<br>
      唯一無二のお時間をご体感できる<br>こと間違いなし★',
            'food' => 'マカロン',
      'character' => '甘えん坊',
      'type' => '面白い人',
      'cast-name' => 'しほり',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'アイドル系',
      'cast-comment' => '目いっぱい楽しい時間を一緒に過ごしましょう！',
      'store-comment' => '「しほりちゃん」は華の現役女子大生！<br>
      黒髪ロングの王道美少女、クラスのマドンナ的存在です！！' ,
      'cast-comment-tab' => '目いっぱい楽しい時間を<br>
      一緒に過ごしましょう！',
      'store-comment-tab' => '「しほりちゃん」は華の現役<br>
      女子大生!黒髪ロングの王道美少女<br>
      クラスのマドンナ的存在です!!' 
    ],[
      'id' => '5',
      'premium' => true, 
      'premium-type'=>'premium-p',
      'store'=>'京橋',
      'name'=>'ゆいか',
      'age'=>'22',
      'img' => '5',
      'time' => '10:00-17:00',
      'tall' => '148',
      'bust' => '82-C',
      'waist' => '60',
      'height' => '82',
      'newface' => true, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => false,
      'tue' => false,
      'wed' => true,
      'thu' => false,
      'fri' => true,
      'sat' => true,
      'date' => '06/10',
      'comment' => 'ドSと言う言葉は彼女のためにある<br>言葉です！施術技術はもちろん<br>某有名店から電撃移籍！',
            'food' => 'ラーメン',
      'character' => 'しっかり',
      'type' => '楽しい人',
      'cast-name' => 'ようこ',
      'tag1' => '高身長',
      'tag2' => '業界未経験',
      'tag3' => '清楚系',
      'cast-comment' => '優しくしてくれたら懐きます!!',
      'store-comment' => '一生懸命なマジメ系美女！<br>
      先生に満足して頂くために、一生懸命勉強したいとのこと！',
      'cast-comment-tab' => '優しくしてくれたら懐きます!!',
      'store-comment-tab' => '一生懸命なマジメ系美女！<br>
      先生に満足して頂くために、<br>
      一生懸命勉強したいとのこと！'
    ],[
      'id' => '6',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'日本橋',
      'name'=>'あかり',
      'age'=>'20',
      'img' => '6',
      'time' => '10:00-18:00',
      'tall' => '158',
      'bust' => '83-C',
      'waist' => '58',
      'height' => '82',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => false,
      'tue' => true,
      'wed' => true,
      'thu' => false,
      'fri' => true,
      'sat' => false,
      'date' => '',
      'comment' => '果実のように熟したそのお胸は密着<br>エステにおいてはこの上ない幸福な<br>お時間をご提供いたします。',
            'food' => '天ぷら',
      'character' => '真面目',
      'type' => '賢い人',
      'cast-name' => 'ひろ',
      'tag1' => 'ミニマム',
      'tag2' => '業界未経験',
      'tag3' => '清楚系',
      'cast-comment' => '優しくリードしてください',
      'store-comment' => '19歳！美白美女！サラサラ黒髪！そして完全業界未経験！<br>
      紳士な先生だけに限定です！' ,
      'cast-comment-tab' => '優しくリードしてください',
      'store-comment-tab' => '19歳！美白美女！サラサラ黒髪！<br>
      そして完全業界未経験！<br>
      紳士な先生だけに限定です！' 
        ],[     
      'id' => '7',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'梅田',
      'name'=>'めいさ',
      'age'=>'27',
      'img' => '7',
      'time' => '10:00-18:00',
      'tall' => '166',
      'bust' => '89-G',
      'waist' => '62',
      'height' => '88',
      'newface' => true, 
      'pickup' => false, 
      'kuchikomi' => true, 
      'kuchikomi-name' => 'スラ坊', 
      'kuchikomi-star' => '★★★★★', 
      'kuchikomi-title' => '国宝級のボディ。『Ｇ』は伊達じゃない', 
      'kuchikomi-comment' => '人懐っこく可愛がってあげたくなってしまう女性です。<br>
      個人的にほぼ写真通りの雰囲気の女の子でした。タイプはロリ巨乳系。<br>
      ギャルっぽい感じで少しさばさばしていますが、
      その性格のおかげで奥手の私もスグに打ち解けれました。<br>
      終始笑顔でとにかくお顔が近い！！(最高!!)<br><br>
      手を放す事無くずっとお顔の距離が近いのでまるで彼女のようなひと時が味わえて今でも忘れられません…',
      'sun' => true,
      'mon' => false,
      'tue' => true,
      'wed' => false,
      'thu' => false,
      'fri' => true,
      'sat' => false,
      'date' => '06/28',
      'comment' => '引き締まったボディに二度見級の<br>抜群のフェイス！多くは語りません。
      <br>是非一度ご体感くださいませ。',
            'food' => 'アイス',
      'character' => '控えめ',
      'type' => '優しい男性',
      'cast-name' => 'かえ',
      'tag1' => 'ミニマム',
      'tag2' => '業界未経験',
      'tag3' => 'アイドル系',
      'cast-comment' => '経験の少ない私ですが精一杯頑張ります！',
      'store-comment' => '某国民的アイドルグループに入ればセンターとること間違い無し<br>
      今世紀最高の美女です！そのルックスに待ったなし！',
      'cast-comment-tab' => '経験の少ない私ですが<br>
      精一杯頑張ります！',
      'store-comment-tab' => '某国民的アイドルグループに入れば<br>
      センターとること間違い無し<br>
      今世紀最高の美女です！<br>
      そのルックスに待ったなし！'
    ],[
      'id' => '8',
      'premium' => true, 
      'premium-type'=>'',
      'store'=>'京橋',
      'name'=>'まい',
      'age'=>'22',
      'img' => '8',
      'time' => '10:00-18:00',
      'tall' => '151',
      'bust' => '88-G',
      'waist' => '58',
      'height' => '80',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => false,
      'mon' => true,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => false,
      'sat' => true,
      'date' => '',
      'comment' => '施術センス抜群！リピーター様続出<br>全てにおいてエクセレントな<br>女性です。',
            'food' => '梅にぎり',
      'character' => 'おっとり',
      'type' => '大人な人',
      'cast-name' => 'ひかり',
      'tag1' => 'ミニマム',
      'tag2' => '業界未経験',
      'tag3' => 'ロリ系',
      'cast-comment' => '優しいご指導お願いします。',
      'store-comment' => '純粋無垢でつぶらなお目目のロリフェイス！顔のパーツと<br>
      小さな身長に大きなおっぱい…、これぞまさに黄金比率！！',
      'cast-comment-tab' => '優しいご指導お願いします。',
      'store-comment-tab' => '純粋無垢でつぶらなお目目の<br>
      ロリフェイス！顔のパーツと<br>
      小さな身長に大きなおっぱい…、<br>
      これぞまさに黄金比率！！'
    ],[
      'id' => '9',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'難波',
      'name'=>'まりえ',
      'age'=>'24',
      'img' => '9',
      'time' => '12:00-20:00',
      'tall' => '160',
      'bust' => '88-F',
      'waist' => '60',
      'height' => '88',
      'newface' => false, 
      'pickup' => true, 
      'kuchikomi' => false, 
      'sun' => false,
      'mon' => true,
      'tue' => false,
      'wed' => true,
      'thu' => true,
      'fri' => false,
      'sat' => true,
      'date' => '',
      'comment' => '幼さ残るロリ巨乳ちゃん。<br>施術中豹変する恐れあり。<br>Mの方ご注意くださいませ。',
            'food' => 'オムライス',
      'character' => '元気',
      'type' => 'よく笑う人',
      'cast-name' => 'ちなつ',
      'tag1' => 'ミニマム',
      'tag2' => '業界未経験',
      'tag3' => '癒し系',
      'cast-comment' => '一緒に楽しい時間を過ごしましょう!!',
      'store-comment' => 'ボブヘアが可愛い美少女ちなつちゃん!素直で従順な性格も<br>
      良し！いつでもニコニコな彼女にハマること間違いなし!!' ,
      'cast-comment-tab' => '一緒に楽しい時間を過ごしましょう!!',
      'store-comment-tab' => 'ボブヘアが可愛い美少女ちなつちゃん!<br>
      素直で従順な性格も良し!いつでも<br>
      笑顔な彼女にハマること間違いなし!!' 
    ],[
      'id' => '10',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'日本橋',
      'name'=>'えいみ',
      'age'=>'18',
      'img' => '10',
      'time' => '12:00-19:00',
      'tall' => '152',
      'bust' => '83-C',
      'waist' => '58',
      'height' => '85',
      'newface' => true, 
      'pickup' => true, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => true,
      'tue' => false,
      'wed' => false,
      'thu' => true,
      'fri' => true,
      'sat' => false,
      'date' => '06/11',
      'comment' => 'スレンダーでとても綺麗な<br>セラピストです★気配り上手で<br>妖艶な施術必見！楽しい時間になる',
            'food' => 'ピノ',
      'character' => '小悪魔系',
      'type' => '好きになった人',
      'cast-name' => 'ちひろ',
      'tag1' => '巨乳',
      'tag2' => '業界未経験',
      'tag3' => 'ロリ系',
      'cast-comment' => 'わからないことだらけだから優しく教えてくださいっ',
      'store-comment' => 'キレイな黒髪に色白な肌がまぶしいロリ系美少女!!<br>
      スタイルも抜群で面接時からドキドキの扉が開きっぱなしです！',
      'cast-comment-tab' => 'わからないことだらけだから<br>
      優しく教えてくださいっ',
      'store-comment-tab' => 'キレイな黒髪に色白な肌がまぶしい<br>
      ロリ系美少女!!スタイルも抜群で面接時<br>
      からドキドキの扉が開きっぱなしです!'
    ],[
      'id' => '11',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'難波',
      'name'=>'あいか',
      'age'=>'21',
      'img' => '11',
      'time' => '12:00-19:00',
      'tall' => '152',
      'bust' => '85-D',
      'waist' => '60',
      'height' => '82',
      'newface' => true, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => true,
      'tue' => false,
      'wed' => true,
      'thu' => false,
      'fri' => false,
      'sat' => true,
      'date' => '05/27',
      'comment' => '輝かしいHカップは世の男性の<br>大好きなカップ！癒し要素たっぷりの<br>彼女のラブエステをご堪能ください。',
            'food' => 'いちご',
      'character' => '甘えん坊',
      'type' => '強い人',
      'cast-name' => 'ゆう',
      'tag1' => 'ミニマム',
      'tag2' => '業界未経験',
      'tag3' => 'ロリ系',
      'cast-comment' => '甘えさせてください!!',
      'store-comment' => 'ロリ巨乳の最強ツインテール!ロリ好きにはたまらないルックス。<br>
      みんなの妹的存在の美少女です!!',
      'cast-comment-tab' => '甘えさせてください!!',
      'store-comment-tab' => 'ロリ巨乳の最強ツインテール!<br>
      ロリ好きにはたまらないルックス。<br>
      みんなの妹的存在の美少女です!!'
    ],[ 
      'id' => '12',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'梅田',
      'name'=>'りょう',
      'age'=>'21',
      'img' => '12',
      'time' => '18:00-22:00',
      'tall' => '150',
      'bust' => '85(D)',
      'waist' => '59',
      'height' => '81',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => true,
      'tue' => false,
      'wed' => true,
      'thu' => true,
      'fri' => false,
      'sat' => false,
      'date' => '',
      'comment' => '色白で綺麗・スタイル抜群！<br>
      言葉責め好きなM様要チェックです<br>相当エロいですw',
            'food' => '海鮮',
      'character' => 'おっとり',
      'type' => '器用な人',
      'cast-name' => 'れい',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => '癒し系',
      'cast-comment' => 'はじめまして！れいです♪',
      'store-comment' => 'スベスベで張りのある触り心地抜群のＤカップ乳を搭載の<br>
      敏感美女ですよ！予約の確認はマストです!!'
      ,
      'cast-comment-tab' => 'はじめまして！れいです♪',
      'store-comment-tab' => 'スベスベで張りのある触り心地抜群の<br>
      Ｄカップ乳を搭載の敏感美女ですよ!<br>
      敏感美女です!予約の確認はマスト!!'
    ],[ 
      'id' => '13',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'梅田',
      'name'=>'えり',
      'age'=>'21',
      'img' => '13',
      'time' => '18:00-22:00',
      'tall' => '160',
      'bust' => '82-B',
      'waist' => '58',
      'height' => '80',
      'newface' => false, 
      'pickup' => true, 
      'kuchikomi' => false, 
      'sun' => false,
      'mon' => true,
      'tue' => true,
      'wed' => true,
      'thu' => true,
      'fri' => false,
      'sat' => true,
      'date' => '',
      'comment' => '最高の接客力・ルックス！<br>
      誰もが認める美人さんです。恋を<br>しないように注意してください。',
            'food' => '焼き魚',
      'character' => '真面目',
      'type' => '可愛い人',
      'cast-name' => 'かえで',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => '清楚系',
      'cast-comment' => '選んでもらえてよかったと思われるように頑張ります!',
      'store-comment' => '理屈抜きで見た目もオーラも超一流の存在。<br>
      貴方は一目見た瞬間に彼女のトリコになっているでしょう！',
      'cast-comment-tab' => '選んでもらえてよかったと<br>
      思われるように頑張ります!',
      'store-comment-tab' => '理屈抜きで見た目もオーラも超一流の<br>
      存在。貴方は一目見た瞬間に<br>
      彼女のトリコになっているでしょう！'
    ],[
      'id' => '14',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'日本橋',
      'name'=>'あきら',
      'age'=>'25',
      'img' => 'ng',
      'time' => '20:00-2:00',
      'tall' => '170',
      'bust' => '85-D',
      'waist' => '62',
      'height' => '85',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => false,
      'mon' => true,
      'tue' => false,
      'wed' => true,
      'thu' => false,
      'fri' => false,
      'sat' => true,
      'date' => '',
      'comment' => '未経験からのスタートになりますが<br>とても可愛く妖艶なセラピストです<br>お勧め度MAXです！',
            'food' => 'オレンジ',
      'character' => '元気',
      'type' => '優しい人',
      'cast-name' => 'ゆうひ',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'ギャル系',
      'cast-comment' => '元気をいっぱい分けてあげるね☆',
      'store-comment' => 'プレミアム美少女の入店決定！屈託の無い透き通った大きな<br>
      ひとみはブラックホールよりも引き寄せられます！！'
      ,
      'cast-comment-tab' => '元気をいっぱい分けてあげるね☆',
      'store-comment-tab' => 'プレミアム美少女の入店決定!
      屈託の無い透き通った大きなひとみは<br>
      ブラックホールよりも引き寄せられます!!'
    ],[ 
      'id' => '15',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'京橋',
      'name'=>'なぎさ',
      'age'=>'22',
      'img' => '15',
      'time' => '20:00-2:00',
      'tall' => '158',
      'bust' => '85-C',
      'waist' => '60',
      'height' => '86',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => false,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => true,
      'sat' => true,
      'date' => '',
      'comment' => 'モデル顔負けのルックスに誰もが<br>認める性格の良さ！お客様を大事に<br>思う心はNo1でございます。',
            'food' => 'からあげ',
      'character' => '甘えん坊',
      'type' => '包容力のある人',
      'cast-name' => 'なつみ',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => '癒し系',
      'cast-comment' => '甘えてもいいかな？',
      'store-comment' => 'すぐに抱きついてきてイチャイチャしたがる「なつみちゃん」の<br>
      甘えた攻撃は、ある意味”一撃必殺クラス”！？' ,
      'cast-comment-tab' => '甘えてもいいかな？',
      'store-comment-tab' => 'すぐに抱きついてきてイチャイチャしたがる<br>
      「なつみちゃん」の甘えた攻撃は、<br>
      ある意味”一撃必殺クラス”！？' 
      
    ],[
      'id' => '16',
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'難波',
      'name'=>'いおり',
      'age'=>'21',
      'img' => 'ng',
      'time' => '20:00-3:00',
      'tall' => '156',
      'bust' => '84-D',
      'waist' => '62',
      'height' => '88',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => false,
      'mon' => true,
      'tue' => true,
      'wed' => true,
      'thu' => false,
      'fri' => false,
      'sat' => true,
      'date' => '',
      'comment' => 'お勧めの美人セラピストさんです。<br>
      未経験からのスタートですが講習も<br>楽々クリア。お勧めの美人さんです',
            'food' => '辛いもの',
      'character' => '元気',
      'type' => '面白い人',
      'cast-name' => 'くるみ',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'ギャル系',
      'cast-comment' => '楽しいことが大好きです！仲良くなりましょう♪',
      'store-comment' => 'THEイマドキの女の子なくるみちゃん!元気でエネルギッシュな
      <br>くるみちゃんといれば素敵な時間になること間違いなし!' ,
      'cast-comment-tab' => '楽しいことが大好きです！<br>
      仲良くなりましょう♪',
      'store-comment-tab' => 'THEイマドキの女の子なくるみちゃん!<br>
      元気でエネルギッシュなくるみちゃんと<br>
      いれば素敵な時間になること<br>
      間違いなし!' 
    ],[   
      'id' => '17', 
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'難波',
      'name'=>'あいか',
      'age'=>'21',
      'img' => '17',
      'time' => '23:00-3:00',
      'tall' => '152',
      'bust' => '83-C',
      'waist' => '60',
      'height' => '82',
      'newface' => false, 
      'pickup' => true, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => false,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => false,
      'sat' => false,
      'date' => '',
      'comment' => 'スタイル抜群・施術上手・性格抜群<br>
      かなり人気のセラピストになります<br>事前予約必須！',
            'food' => 'お米',
      'character' => '天然',
      'type' => '笑顔が多い人',
      'cast-name' => 'かすみ',
      'tag1' => '巨乳',
      'tag2' => '業界未経験',
      'tag3' => 'アイドル系',
      'cast-comment' => '不慣れな点もありますがよろしくお願いします♪',
      'store-comment' => '清純派アイドルさながらの超絶美人が入店です！<br>
      話のストックも多くてどんな人とも仲良くなることでしょう！？' ,
      'cast-comment-tab' => '不慣れな点もありますが<br>よろしくお願いします♪',
      'store-comment-tab' => '清純派アイドルさながらの超絶美人が<br>
      入店です！話のストックも多く<br>
      どんな人とも仲良くなることでしょう！' 
    ],[ 
      'id' => '18',  
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'難波',
      'name'=>'きらり',
      'age'=>'20',
      'img' => '18',
      'time' => '23:00-4:00',
      'tall' => '160',
      'bust' => '83-C',
      'waist' => '60',
      'height' => '82',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => false,
      'mon' => false,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => true,
      'sat' => true,
      'date' => '',
      'comment' => '顔出しできないのが残念です！<br>とても小顔で色白そして可愛いです。<br>
      自信を持ってお勧めいたします。',
            'food' => '和食',
      'character' => 'マイペース',
      'type' => '紳士的な人',
      'cast-name' => 'なな',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'お姉さん系',
      'cast-comment' => '癒されたい先生はぜひ',
      'store-comment' => '物静かで控えめな性格の「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！そのギャップが味わえるって最高です!!',
      'cast-comment-tab' => '癒されたい先生はぜひ',
      'store-comment-tab' => '物静かで控えめな性格の<br>
      「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！<br>
      そのギャップが味わえるって最高です!!'
    ]            
    ,[ 
      'id' => '19',  
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'梅田',
      'name'=>'まり',
      'age'=>'28',
      'img' => '19',
      'time' => '23:00-3:00',
      'tall' => '150',
      'bust' => '82-C',
      'waist' => '60',
      'height' => '82',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => false,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => false,
      'sat' => true,
      'date' => '',
      'comment' => '顔出しできないのが残念です！<br>とても小顔で色白そして可愛いです。<br>
      自信を持ってお勧めいたします。',
            'food' => '和食',
      'character' => 'マイペース',
      'type' => '紳士的な人',
      'cast-name' => 'なな',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'お姉さん系',
      'cast-comment' => '癒されたい先生はぜひ',
      'store-comment' => '物静かで控えめな性格の「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！そのギャップが味わえるって最高です!!',
      'cast-comment-tab' => '癒されたい先生はぜひ',
      'store-comment-tab' => '物静かで控えめな性格の<br>
      「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！<br>
      そのギャップが味わえるって最高です!!'
    ]   ,[ 
      'id' => '20',  
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'京橋',
      'name'=>'りいさ',
      'age'=>'25',
      'img' => 'ng',
      'time' => '23:00-4:00',
      'tall' => '154',
      'bust' => '88-F',
      'waist' => '62',
      'height' => '85',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => false,
      'tue' => false,
      'wed' => false,
      'thu' => true,
      'fri' => true,
      'sat' => false,
      'date' => '',
      'comment' => '顔出しできないのが残念です！<br>とても小顔で色白そして可愛いです。<br>
      自信を持ってお勧めいたします。',
            'food' => '和食',
      'character' => 'マイペース',
      'type' => '紳士的な人',
      'cast-name' => 'なな',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'お姉さん系',
      'cast-comment' => '癒されたい先生はぜひ',
      'store-comment' => '物静かで控えめな性格の「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！そのギャップが味わえるって最高です!!',
      'cast-comment-tab' => '癒されたい先生はぜひ',
      'store-comment-tab' => '物静かで控えめな性格の<br>
      「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！<br>
      そのギャップが味わえるって最高です!!'
    ]   ,[ 
      'id' => '21',  
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'日本橋',
      'name'=>'ゆう',
      'age'=>'20',
      'img' => '21',
      'time' => '23:00-5:00',
      'tall' => '172',
      'bust' => '84-B',
      'waist' => '60',
      'height' => '80',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => false,
      'mon' => false,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => true,
      'sat' => true,
      'date' => '',
      'comment' => '顔出しできないのが残念です！<br>とても小顔で色白そして可愛いです。<br>
      自信を持ってお勧めいたします。',
            'food' => '和食',
      'character' => 'マイペース',
      'type' => '紳士的な人',
      'cast-name' => 'なな',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'お姉さん系',
      'cast-comment' => '癒されたい先生はぜひ',
      'store-comment' => '物静かで控えめな性格の「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！そのギャップが味わえるって最高です!!',
      'cast-comment-tab' => '癒されたい先生はぜひ',
      'store-comment-tab' => '物静かで控えめな性格の<br>
      「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！<br>
      そのギャップが味わえるって最高です!!'
    ]   ,[ 
      'id' => '22',  
      'premium' => false, 
      'premium-type'=>'',
      'store'=>'梅田',
      'name'=>'さりな',
      'age'=>'25',
      'img' => '22',
      'time' => '23:00-5:00',
      'tall' => '165',
      'bust' => '85-D',
      'waist' => '60',
      'height' => '82',
      'newface' => false, 
      'pickup' => false, 
      'kuchikomi' => false, 
      'sun' => true,
      'mon' => true,
      'tue' => true,
      'wed' => false,
      'thu' => true,
      'fri' => false,
      'sat' => false,
      'date' => '',
      'comment' => '顔出しできないのが残念です！<br>とても小顔で色白そして可愛いです。<br>
      自信を持ってお勧めいたします。',
            'food' => '和食',
      'character' => 'マイペース',
      'type' => '紳士的な人',
      'cast-name' => 'なな',
      'tag1' => 'スレンダー',
      'tag2' => '業界未経験',
      'tag3' => 'お姉さん系',
      'cast-comment' => '癒されたい先生はぜひ',
      'store-comment' => '物静かで控えめな性格の「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！そのギャップが味わえるって最高です!!',
      'cast-comment-tab' => '癒されたい先生はぜひ',
      'store-comment-tab' => '物静かで控えめな性格の<br>
      「ななちゃん」ですが、内に秘めた<br>
      ポテンシャルは当店随一！<br>
      そのギャップが味わえるって最高です!!'
    ]                            
  ];
      ?>